### ISSUE TITLE
Scoreboard Bug for itemsadder 

### ISSUE THREAD

**Issue by Distolfix** [LoneDev6/Wiki-ItemsAdder#74]
I noticed inconsistencies between the guide and the scoreboard settings. First, %img_offset_-500% doesn't seem to work properly.
![prova1](https://user-images.githubusercontent.com/73421268/223709456-2f4757f8-bf85-46ea-9d5a-402e3fe3f0f2.png)

![image](https://user-images.githubusercontent.com/73421268/223709516-dea3e57d-2579-4949-829f-8e9dae0604df.png)

Also I don't know if it's your plugin but there is a problem with the emojis on the scoreboard. I noticed that even though I insert the emoji and load the texturepack, this symbol comes out.

![image](https://user-images.githubusercontent.com/73421268/223709752-f384c74a-c2a0-4cfa-9509-48e7b00415e3.png)

It happened to all of us who are working in the server. (only on the scoreboard).  although everything else worked fine.

But as soon as I deleted my .minecraft and re-entered it showed my scoreboard correctly.

So I kindly ask you to add a warning. Because for this problem I lost hours and hours. When I then tried this it worked. so whoever happens to not waste timeI. don't know if it's a plugin problem but I report it on the site. Maybe because with updates of your plugin the variables have changed and are no longer functional.

Thanks!!

**Comment by LoneDev6** [comment]
Provide your full scoreboard configuration and the name of the scoreboard plugin you're using.
The tutorials were tested carefully and working on two plugins, so there surely is a little mistake or incompatibility.
https://itemsadder.devs.beer/plugin-usage/hide-scoreboard-numbers-1.17+

**Comment by LoneDev6** [comment]
Anyway please next time open the issue report on the [correct Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues).
I wonder why you totally skipped reading that:
![image](https://user-images.githubusercontent.com/27242001/223746086-25d60eb3-0824-4061-98e0-39c699c2b535.png)

**Comment by Distolfix** [comment]
Hi, I still have another small error to report to you but I'm having difficulty opening it. I am sending you a small log I hope you will tell me why it gives me this error. I'm sorry and I hope for your clemency, my intent is not to make you nervous I just want to help you solve small problems https://pastebin.com/aXCqbYZL

However I have used all your plugins updated to the latest version on the site regarding the issues I reported to you yesterday.
I also used the plugin you used in the guide but it doesn't work. i used featherboard in these screens. I think it depends on 1.19.3. 

![image](https://user-images.githubusercontent.com/73421268/223996834-e86f0fec-511e-4abc-aaab-a538b116fd36.png)

Another small thing (/version pluginname with cmi doesn't work) 

LoneLibs:

![image](https://user-images.githubusercontent.com/73421268/223997366-3c553a25-6348-4054-9a91-cf71491f9475.png)


ProtocolLib: 

![image](https://user-images.githubusercontent.com/73421268/223997424-e33b20ab-d9f9-447f-98a7-6d74afd21189.png)

ItemsAdder_3.4.0b-beta version.

**Comment by LoneDev6** [comment]
Make sure you have the latest Citizens installed, it seems to be the issue.
https://ci.citizensnpcs.co/job/citizens2/

**Comment by Distolfix** [comment]
[13:38:30 ERROR]: Error occurred (in the plugin loader) while disabling ItemsAdder v3.4.0b-beta (Is it up to date?)
java.lang.IllegalStateException: no implementation set
        at net.citizensnpcs.api.CitizensAPI.getImplementation(CitizensAPI.java:84) ~[Citizens-2.0.30-b2960.jar:?]
        at net.citizensnpcs.api.CitizensAPI.getTraitFactory(CitizensAPI.java:168) ~[Citizens-2.0.30-b2960.jar:?]
        at dev.lone.itemsadder.Core.OtherPlugins.Citizens.CitizensHook.unregister(SourceFile:45) ~[ItemsAdder_3.4.0b-beta.jar:?]
        at dev.lone.itemsadder.Main.onDisable(SourceFile:628) ~[ItemsAdder_3.4.0b-beta.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:227) ~[paper-1.19.3.jar:git-Paper-425]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:151) ~[paper-1.19.3.jar:git-Paper-425]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:92) ~[paper-1.19.3.jar:git-Paper-425]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:528) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.disablePlugins(CraftServer.java:492) ~[paper-1.19.3.jar:git-Paper-425]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:944) ~[paper-1.19.3.jar:git-Paper-425]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:804) ~[paper-1.19.3.jar:git-Paper-425]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1212) ~[paper-1.19.3.jar:git-Paper-425]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-425]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        
        The same

**Comment by LoneDev6** [comment]
There might be another plugin interfering, anyway I'll check again to confirm that.
Last time i tested Citizens worked fine with ItemsAdder.
